// todo-vue (OLD)/src/components/TaskItem.vue
<!--
  TASK ITEM COMPONENT: Displays and manages a single task

  This component demonstrates the most Vue concepts:
  - Props with validation
  - Multiple emits for different events
  - Conditional rendering (v-if) for display/edit modes
  - Local state (isEditing, editText) for UI-only concerns
  - Class binding with objects
-->

<template>
  <li :class="['task-item', { completed: task.completed }]">
    <!-- CHECKBOX: Toggle task completion -->
    <input
      type="checkbox"
      class="task-checkbox"
      :checked="task.completed"
      @change="$emit('toggle', task.id)"
    />

    <!-- DISPLAY MODE: Show task text when not editing -->
    <span v-if="!isEditing" class="task-text">{{ task.text }}</span>

    <!-- EDIT MODE: Show input field when editing -->
    <input
      v-if="isEditing"
      v-model="editText"
      @keypress.enter="saveEdit"
      @keyup.esc="cancelEdit"
      class="task-input"
      type="text"
      ref="editInput"
    />

    <div class="task-actions">
      <!-- DISPLAY MODE BUTTONS: Edit and Delete -->
      <template v-if="!isEditing">
        <button @click="startEdit" class="btn-edit">Edit</button>
        <button @click="confirmDelete" class="btn-delete">Delete</button>
      </template>

      <!-- EDIT MODE BUTTONS: Save and Cancel -->
      <template v-if="isEditing">
        <button @click="saveEdit" class="btn-save">Save</button>
        <button @click="cancelEdit" class="btn-cancel">Cancel</button>
      </template>
    </div>
  </li>
</template>

<script>
export default {
  name: 'TaskItem',

  // PROPS: Task object passed from parent
  props: {
    task: {
      type: Object,
      required: true
    }
  },

  // EMITS: Events this component can fire
  // Parent decides what to do - this component just signals "something happened"
  emits: ['toggle', 'delete', 'update'],

  data() {
    return {
      // Local state for UI-only concerns (not shared with parent)
      isEditing: false,
      editText: ''
    }
  },

  methods: {
    // Enter edit mode - store current text for potential cancel
    startEdit() {
      this.editText = this.task.text
      this.isEditing = true

      // $nextTick waits for Vue to re-render before running code
      // We need this because the input doesn't exist in DOM until v-if shows it
      this.$nextTick(() => {
        if (this.$refs.editInput) {
          this.$refs.editInput.focus()
          this.$refs.editInput.select()
        }
      })
    },

    // Save changes - emit 'update' event to parent
    saveEdit() {
      const newText = this.editText.trim()

      if (!newText) {
        alert('Task cannot be empty!')
        return
      }

      // Emit event with task id and new text - parent handles the API call
      this.$emit('update', this.task.id, newText)
      this.isEditing = false
    },

    // Cancel edit - revert to display mode without saving
    cancelEdit() {
      this.isEditing = false
      this.editText = ''
    },

    // Confirm before deleting
    confirmDelete() {
      if (confirm('Are you sure you want to delete this task?')) {
        this.$emit('delete', this.task.id)
      }
    }
  }
}
</script>

<style scoped>
.task-item {
  background: #f9f9f9;
  padding: 12px;
  margin-bottom: 8px;
  border-radius: 4px;
  border: 1px solid #e0e0e0;
  display: flex;
  align-items: center;
  gap: 10px;
}

.task-item:hover {
  background: #f0f0f0;
}

.task-item.completed {
  opacity: 0.6;
}

.task-item.completed .task-text {
  text-decoration: line-through;
  color: #999;
}

.task-checkbox {
  width: 20px;
  height: 20px;
  cursor: pointer;
}

.task-text {
  flex: 1;
  font-size: 16px;
  color: #333;
  word-break: break-word;
}

.task-input {
  flex: 1;
  padding: 8px;
  border: 2px solid #667eea;
  border-radius: 5px;
  font-size: 16px;
}

.task-actions {
  display: flex;
  gap: 5px;
}

.btn-edit,
.btn-delete,
.btn-save,
.btn-cancel {
  padding: 6px 12px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  color: white;
}

.btn-edit {
  background: #2196F3;
}
.btn-edit:hover {
  background: #0b7dda;
}

.btn-delete {
  background: #f44336;
}
.btn-delete:hover {
  background: #da190b;
}

.btn-save {
  background: #4CAF50;
}
.btn-save:hover {
  background: #45a049;
}

.btn-cancel {
  background: #999;
}
.btn-cancel:hover {
  background: #777;
}
</style>

// todo-react/src/components/TaskItem.jsx
// TASK ITEM COMPONENT: Displays and manages a single task
// REACT VERSION of TaskItem.vue - demonstrates useState, useRef, useEffect

import React, { useState, useRef, useEffect } from 'react'

function TaskItem({ task, onToggle, onDelete, onUpdate }) {
  // MULTIPLE useState HOOKS - replaces Vue's data() with multiple properties
  // In Vue: data() { return { isEditing: false, editText: '' }}
  // In React: separate useState for each piece of state
  const [isEditing, setIsEditing] = useState(false)
  const [editText, setEditText] = useState('')

  // useRef - replaces Vue's ref="editInput" for DOM access
  // This gives us direct access to the input element
  const editInputRef = useRef(null)

  // useEffect - replaces Vue's $nextTick
  // Runs AFTER the component re-renders
  // The [isEditing] dependency means "run this when isEditing changes"
  useEffect(() => {
    if (isEditing && editInputRef.current) {
      editInputRef.current.focus()
      editInputRef.current.select()
    }
  }, [isEditing])

  // Enter edit mode - replaces Vue's startEdit method
  const startEdit = () => {
    setEditText(task.text)
    setIsEditing(true)
    // Notice: no more $nextTick - useEffect handles the focus automatically!
  }

  // Save changes - emit update to parent
  const saveEdit = () => {
    const newText = editText.trim()

    if (!newText) {
      alert('Task cannot be empty!')
      return
    }

    // Call parent function - replaces Vue's $emit('update', ...)
    onUpdate(task.id, newText)
    setIsEditing(false)
  }

  // Cancel edit - revert to display mode
  const cancelEdit = () => {
    setIsEditing(false)
    setEditText('')
  }

  // Confirm before deleting
  const confirmDelete = () => {
    if (confirm('Are you sure you want to delete this task?')) {
      onDelete(task.id)
    }
  }

  // Handle keyboard shortcuts in edit mode
  const handleKeyDown = (e) => {
    if (e.key === 'Enter') saveEdit()
    if (e.key === 'Escape') cancelEdit()
  }

  return (
    <li className={`task-item ${task.completed ? 'completed' : ''}`}>
      {/* CHECKBOX: Toggle task completion */}
      <input
        type="checkbox"
        className="task-checkbox"
        checked={task.completed}
        onChange={() => onToggle(task.id)}
      />

      {/* CONDITIONAL RENDERING - replaces Vue's v-if */}
      {/* In Vue: v-if="!isEditing" */}
      {/* In React: {!isEditing && (<element>)} OR ternary operator */}
      {!isEditing ? (
        <span className="task-text">{task.text}</span>
      ) : (
        <input
          ref={editInputRef}
          value={editText}
          onChange={(e) => setEditText(e.target.value)}
          onKeyDown={handleKeyDown}
          className="task-input"
          type="text"
        />
      )}

      <div className="task-actions">
        {/* CONDITIONAL RENDERING WITH TERNARY - show different buttons based on mode */}
        {!isEditing ? (
          <>
            <button onClick={startEdit} className="btn-edit">Edit</button>
            <button onClick={confirmDelete} className="btn-delete">Delete</button>
          </>
        ) : (
          <>
            <button onClick={saveEdit} className="btn-save">Save</button>
            <button onClick={cancelEdit} className="btn-cancel">Cancel</button>
          </>
        )}
      </div>
    </li>
  )
}

export default TaskItem
