// todo-vue (OLD)/src/components/TaskForm.vue
<!--
  TASK FORM COMPONENT: Reusable input for adding new tasks

  COMPONENT COMMUNICATION PATTERN:
  - This component is a CHILD of TodoView
  - Child doesn't directly modify parent's data
  - Instead, it EMITS events, and parent decides what to do
  - This is the "props down, events up" pattern - a core Vue principle
-->

<template>
  <div class="input-section">
    <!--
      v-model creates two-way binding with local data 'newTaskText'
      @keypress.enter is Vue's shorthand for "when Enter key is pressed"
    -->
    <input
      type="text"
      v-model="newTaskText"
      @keypress.enter="submitTask"
      placeholder="Enter a new task..."
    />
    <button @click="submitTask" class="btn btn-add">Add Task</button>
  </div>
</template>

<script>
export default {
  name: 'TaskForm',

  // EMITS: Explicitly declares what events this component can emit
  // This is optional but good practice - makes the component's API clear
  emits: ['add-task'],

  data() {
    return {
      newTaskText: ''  // Local state for the input field
    }
  },

  methods: {
    submitTask() {
      const text = this.newTaskText.trim()

      // Don't emit empty tasks
      if (!text) {
        alert('Please enter a task!')
        return
      }

      // EMIT: Send data to parent component
      // Parent (TodoView) listens with @add-task="handleAddTask"
      this.$emit('add-task', text)

      // Clear input after submitting
      this.newTaskText = ''
    }
  }
}
</script>

<style scoped>
/* Styles scoped to only this component */
.input-section {
  display: flex;
  gap: 10px;
  margin-bottom: 20px;
}

input {
  flex: 1;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 16px;
}

input:focus {
  outline: none;
  border-color: #4CAF50;
}

.btn-add {
  background: #4CAF50;
  color: white;
}

.btn-add:hover {
  background: #45a049;
}
</style>

// todo-react/src/components/TaskForm.jsx
// TASK FORM COMPONENT: Reusable input for adding new tasks
// REACT VERSION of TaskForm.vue

import React, { useState } from 'react'

function TaskForm({ onAddTask }) {
  // REACT STATE - replaces Vue's data() function
  // In Vue: data() { return { newTaskText: '' }}
  // In React: useState hook
  const [newTaskText, setNewTaskText] = useState('')

  // EVENT HANDLER - replaces Vue's methods
  const submitTask = () => {
    const text = newTaskText.trim()

    // Don't submit empty tasks
    if (!text) {
      alert('Please enter a task!')
      return
    }

    // CALL PARENT FUNCTION - replaces Vue's $emit
    // In Vue: this.$emit('add-task', text)
    // In React: call the function passed as prop
    onAddTask(text)

    // Clear input after submitting
    setNewTaskText('')
  }

  // HANDLE ENTER KEY - React way of handling keypress
  const handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      submitTask()
    }
  }

  // REACT RETURN - replaces Vue's <template>
  return (
    <div className="input-section">
      {/* CONTROLLED COMPONENT - React's version of v-model */}
      <input
        type="text"
        value={newTaskText}                           // Current value from state
        onChange={(e) => setNewTaskText(e.target.value)}  // Update state when user types
        onKeyPress={handleKeyPress}                  // Handle Enter key
        placeholder="Enter a new task..."
      />
      <button onClick={submitTask} className="btn btn-add">
        Add Task
      </button>
    </div>
  )
}

export default TaskForm
